### ISSUE TITLE
[Suggestion] Show "Things/t" on Trash Blocks

### ISSUE THREAD

**Issue by Endgineer** [tgstyle/MCT-Immersive-Technology#113]
While aiming on the (item/fluid/energy) trash cans, I noticed that values are shown as "X things in the last second". It would be nice if there was a config option to show "X things/t". Alternatively, maybe IE-style gauges (blocks that would show the rates when hovered over) could be added instead.

Thanks for the work you do on updating/working on the mod.

**Comment by Kurtchekov** [comment]
The problem is that some mods, such as Thermal Dynamics, transfer items only twice per second or even just once per second. So, if we were to display per tick, it'd be flipping between 0 and X all the time. The other option is to calculate the average per second, for example, and display the amount per tick. We're afraid players might get confused by that.

**Comment by Endgineer** [comment]
Oh I see. And by average per second, I assume (X things in the last second)/20? If so, that's exactly what I was hoping for (I was gunning for the easy solution from the get-go :P). An option to show that number would be nice, since currently I'm sorta resorting to manually doing the division everytime I want to see rates. It would be nice to just see rates in-game.

It could be a config option (i.e. show either X in last second OR average per tick taken over last second).

**Comment by Kurtchekov** [comment]
[IT.zip](https://github.com/tgstyle/MCT-Immersive-Technology/files/4497097/IT.zip)
Here's an experimental build so that you can check out this feature already. Unzip it and replace the current immersive technology jar you have there with this one. Run the game once so that it can generate the option in your config file. In the Experimental category of this mod's config file, change per_tick_trash_cans to true. It should now display the old value but divided by 20.

**Comment by Endgineer** [comment]
Works nicely.
