### ISSUE TITLE
Placing Fluid Pumps causes crashing.

### ISSUE THREAD

**Issue by TechLord22** [tgstyle/MCT-Immersive-Technology#116]
I am getting this crash error:
`java.lang.ClassCastException: mctmods.immersivetechnology.common.blocks.metal.tileentities.TileEntityFluidPump cannot be cast to blusunrize.immersiveengineering.common.blocks.metal.TileEntityFluidPumpat flaxbeard.immersivepetroleum.common.items.ItemProjector.handlePumpPlace(ItemProjector.java:1020)`
when I try to place the fluid pump from regular immersive engineering. This was on version 1.7.59.

People on the minecraft pack development server suggested extending `lusunrize.immersiveengineering.common.blocks.metal.TileEntityFluidPump` instead of making a similar class. 

Full Log (too large for pastebin): https://cdn.discordapp.com/attachments/362322551684464643/707325715380699229/latest.log

**Comment by Kurtchekov** [comment]
@TechLord22 I'm sorry I haven't touched this issue earlier, for some reason I haven't got a notification about it. 

So, the problem about extending the original class is that it has some private fields I can't access from my own class (because they're in different packages), that's why I didn't extend the original class back then. Since this issue is more important than performance, I'm extending that class and re-implementing those fields in my own class. Please, give a try to this build of the mod, just disable Immersive Technology and add this file to your mods folder, no need to rename it.
[IT.zip](https://github.com/tgstyle/MCT-Immersive-Technology/files/4604530/IT.zip)

Lemme know if it works!

**Comment by TechLord22** [comment]
I tried placing the fluid pump in the same world again, and had no issues afterwards. I then tried the version you sent, and tried every multiblock and block that had a function (ones that do something) from Immersive Technology, Immersive Engineering, and Immersive Petroleum and found no issues. I think this was some sort of one-off crash, and I am not sure why it happened in the first place. When I originally had the crash, I was building a bottling machine by sneak right clicking the projector in creative, and then the crash happened. But trying it again no longer crashed with and without the build you supplied. Thanks for putting in the time trying find a solution.

**Comment by Kurtchekov** [comment]
Okay, I've managed to reproduce the bug here. Since the bottling machine uses the IE pump as a building block, whenever you try to use the IP's projector to automatically assemble that multiblock, it crashes the game. I will be pushing the fix in a moment. Thank you for finding such a rare bug!
