### ISSUE TITLE
Ability to keep/use old solar tower in 9.95+

### ISSUE THREAD

**Issue by Biviho** [tgstyle/MCT-Immersive-Technology#235]
i personally think that they are nicer to look at and more fitting with IE and it's steam-diesel punk, so it would be cool to have an option to build the old one instead the new one, if it's a possible thing to do.

alternatively (but more work), include more of the old design into the new one, expecially in reflectors, maybe they could be an inclined version of the old one.

**Comment by voidsong-dragonfly** [comment]
No, because the old one was extremely unrealistic and was entirely unfitting from any mod that has even a semblance of realism. The old ones were made by someone who, while they may have been able to make models, had no concept of what an actual solar power tower designed solar plant looks like. I kept as much as I could but that was only as much as exists in the tower and the textures.
