### ISSUE TITLE
Crash during load of save game with Immersive Tech

### ISSUE THREAD

**Issue by raymondbh** [tgstyle/MCT-Immersive-Technology#56]
Game crashes when trying to load a save game with items from Immersive Tech in it.

Crash log:
https://pastebin.com/pVmcXc4j

**Comment by tgstyle** [comment]
Can we get a copy of the save? Have you tried going to the 1.6 version then to the 1.7 version?

**Comment by raymondbh** [comment]
I will try that first. :)

**Comment by raymondbh** [comment]
Save loads fine with 1.6, but crashes with 1.7... Same error as before.

**Comment by tgstyle** [comment]
@Kurtchekov thoughts? @raymondbh can you provide the savefile?

**Comment by Kurtchekov** [comment]
Our function "RemoveDummyFromTicking" is apparently adding a null value to the list of TEs to be removed. How it does that defies logic since all calls to that function are done by the TEs themselves. If I had to take a guess, the TE in question is getting removed from the world before it's been removed from that list, so I can make a small change to that function so that it checks if they're still valid before trying to remove from the ticking entities list.

**Comment by Kurtchekov** [comment]
@raymondbh Can you try this version of the mod?
[testbuild.zip](https://github.com/tgstyle/MCT-Immersive-Technology/files/4258566/testbuild.zip)
Unzip the testbuild.jar into your mods folder and don't forget to remove any other immersive tech jar from that folder as well.

**Comment by raymondbh** [comment]
Same problem with the testbuild.jar I am afraid.

Savegame and modpack (MultiMC modpack):
https://drive.google.com/file/d/19AsavYQianY9_Zlpl4UpP8tPAzCBqycb/view?usp=sharing

I left the 1.7 versjon enabled, but 1.6 or Immersive Tech are still there to be enabled if you wish.
(In MultiMC you can edit this by "Edit Instance")

**Comment by Kurtchekov** [comment]
@raymondbh Okay, this problem might be caused by one of the other mods, possibly Thaumcraft, but gratefully we can handle this problem on our end. While we prepare to release a new version of the mod, you can play around with this build
[immersivetech.zip](https://github.com/tgstyle/MCT-Immersive-Technology/files/4261352/immersivetech.zip)

**Comment by raymondbh** [comment]
That's great news, I will test it as soon as possible.

Edit: That seems to do the trick! Great work, thank you :)
