### ISSUE TITLE
Boilers Consume 0.5x as much fuel as stated.

### ISSUE THREAD

**Issue by voidsong-dragonfly** [tgstyle/MCT-Immersive-Technology#98]
I have boilers set to consume 10mB/t of biodiesel, and yet no matter what I change with the heat value, etc, they consistently consume 5mB/t of biodiesel. This means that I can run three boilers off of a refinery instead of the correct 1.6, making the power output through steam much higher than it should be.
MC 1.12.2
IE 0.12-92
IT 1.7.54
EDIT: This also happens with 20mB/t, making the boiler consume 10mB/t instead of the full 20. So it's not simply defaulting to 5 mB/t.

**Comment by tgstyle** [comment]
Closed https://github.com/tgstyle/MCT-Immersive-Technology/pull/99

**Comment by Kurtchekov** [comment]
@Silfryi thank you so much for your contributions, this issue was also affecting the steam turbine, making it more efficient than it was supposed to be. Also, that's a very cute profile pic ;D

**Comment by voidsong-dragonfly** [comment]
Oh, the steam turbine was running on 2x less steam than it should have been? Never realized that. Huh.

**Comment by voidsong-dragonfly** [comment]
If it's supposed to consume 100mB/t then my calculations for the PR I did should still hold up.
2000 mB -> 1000mB (1 second) makes 1000/20 = 50mB/t for one boiler on water; if they're meant to consume 200 then they're incorrect. Whenever the newest build comes out I can test to make sure it works.

**Comment by Kurtchekov** [comment]
JEI was displaying the correct numbers, the problem was simply that the boiler and steam turbine weren't counting down the one tick when a process is over and a new one starts, which means that recipes were lasting one more tick than they were supposed to. For recipes that take just 1 tick, the increase is huge, but I hadn't realized because I was using something like 20 ticks for those recipes, which means that they were taking 21 ticks, not all that noticeable =P

**Comment by Kurtchekov** [comment]
So yeah, your changes still apply ^^

**Comment by voidsong-dragonfly** [comment]
Oh, cool. That makes sense! Glad to see the math checks out. I was wondering why I could get so much power out when I shouldn't have been able to and found this, and was pretty glad I did.
